<?php

use \Smartosc\Banner\Block\Adminhtml\Records;

/**
 *  Amasty reason list template
 *
 * @var Records $block
 */

$element = $block->getElement();
$defaultConditionsData = $block->getDefaultRecords();
$selectedConditionsData = $block->getSelectedRecords();
$counter = 0;

$writer = new \Zend_Log_Writer_Stream(BP . '/var/log/logg5.log');
$logger = new \Zend_Log();
$logger->addWriter($writer);
$logger->info(print_r($defaultConditionsData, true));
$logger->info(print_r($selectedConditionsData, true));
?>

<td class="record-label label">
    <label>
        <span>
            <?= $block->escapeHtml(__('Banner based on Website')); ?>
        </span>
    </label>
</td>
<td class="record-conditions-block record-dragndrop-block">
    <div class="record-wrapper"
         data-mage-init='{"bannerRecords":<?= /* @noEscape */
         $block->getInitData() ?>}'>
        <p class="record-legend">
            <span class="title"><?= $block->escapeHtml(__('Website(s) ')) ?></span>
            <span><?= $block->escapeHtml(__('Actions')) ?></span>
        </p>
        <!-- should be empty element to clear all items and save it-->
        <input name="<?= $block->escapeHtmlAttr($block->getElement()->getName()); ?>"
               type="text" disabled class="record-hidden disabled" value=""/>
        <ul class="record-order" data-record-js="items">
            <?php foreach ($selectedConditionsData as $condition): ?>
                <li class="record-item" data-record-js="item">
                    <label class="record-label record-field payment-methods">
                        <select
                            name="<?= $block->escapeHtmlAttr($block->getNamePrefix(Records::WEBSITE_IDS, $counter)); ?>"
                        >
                            <?php foreach ($defaultConditionsData[Records::WEBSITE_IDS] as $method => $methodName): ?>
                                <option
                                    value="<?= $block->escapeHtml($method) ?>" <?= ($method == $condition[Records::WEBSITE_IDS]) ? 'selected' : ''; ?>><?= $block->escapeHtml(__($methodName)) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </label>
                    <button class="record-button -clear -delete"
                            title="<?= $block->escapeHtml(__('Remove Item')); ?>"
                            type="button"
                            data-record-js="remove">
                    </button>
                </li>
                <?php $counter++ ?>
            <?php endforeach ?>
        </ul>
        <button class="record-button"
                title="<?= $block->escapeHtml(__('Add Item')); ?>"
                type="button"
                data-record-js="add">
            <?= $block->escapeHtml(__('Add')); ?>
        </button>
    </div>
</td>
